### ISSUE TITLE
请问这个项目怎么部署到nginx中？

### ISSUE THREAD

**Issue by zsoftbuilder** [Yiuman/bpmn-vue-activiti#10]
build好dist文件后部署到nginx报404错误，我在nginx里root已经指定了dist目录后直接访问就报404错误

**Comment by Yiuman** [comment]
。。文件夹架构截图看下吧

**Comment by Yiuman** [comment]
还没反馈这个问题就关掉了 @zsoftbuilder 。以后这些不是该项目的问题麻烦直接发信息咨询就好，这些不属于项目issues的范畴
