### ISSUE TITLE
请问一下，扩展属性里加的配置在usertask里怎么获取到？

### ISSUE THREAD

**Issue by zsoftbuilder** [Yiuman/bpmn-vue-activiti#12]
请问一下，bpmn的扩展属性（activiti:property）里加的一些配置在java代码里usertask里怎么获取到？

**Comment by Yiuman** [comment]
任务的扩展属性应该可以：
```
RepositoryService repositoryService = getProcessEngine().getRepositoryService();
BpmnModel bpmnModel = repositoryService.getBpmnModel(task.getProcessDefinitionId());
FlowElement flowElement = bpmnModel.getFlowElement(task.getTaskDefinitionKey());
UserTask userTask = (UserTask) flowElement;
List<CustomProperty> customProperties = userTask.getCustomProperties();

```java
这样取吧，你可以试试

**Comment by Yiuman** [comment]
https://github.com/Yiuman/citrus  这个后端项目也实现了部分比较通用的功能，若你也需要实现后端工作流相关功能可以参考下 @zsoftbuilder

**Comment by zsoftbuilder** [comment]
通过编辑器添加的扩展属性，获取到的这个UserTask里的customProperties是空的获取不到配置的role


![1629338622(1)](https://user-images.githubusercontent.com/5617798/129996204-4b5dbbdf-3e41-46c2-9e0c-60fb3fed509f.png)

**Comment by Yiuman** [comment]
那就看下userTask.getExtensionElements里边有没东东吧

**Comment by zsoftbuilder** [comment]
同样是空的，是不是编辑器生成的xml标签有问题呢？activist7不支持这种标签呢？
![1629357667(1)](https://user-images.githubusercontent.com/5617798/130025788-1c20fbee-7612-402e-a7a8-ae0e5e72094a.png)

**Comment by zsoftbuilder** [comment]
请问要直接用UserTask.getAttributes()就能获取到的属性，在编辑器里怎么设置添加？

**Comment by Yiuman** [comment]
我也几个月没碰过这块了，还是自己找下资料吧大兄弟
