### ISSUE TITLE
搭配的是activiti7,有人知道如何获取task配置的表单属性和拓展数据吗

### ISSUE THREAD

**Issue by leo-je** [Yiuman/bpmn-vue-activiti#28]
搭配的是activiti7,有人知道如何获取task配置的表单属性和拓展数据吗

**Comment by Yiuman** [comment]
你指的是在前端获取？ @leo-je

**Comment by leo-je** [comment]
> 你指的是在前端获取？ @leo-je
后端,form属性拿到了,但是拓展属性的配置没有找到

**Comment by Yiuman** [comment]
FlowElement flowElement = bpmnModel.getFlowElement("节点的ID");
flowElement.getExtensionElements()
