### ISSUE TITLE
所有表单输入值错误

### ISSUE THREAD

**Issue by Hack-DJ** [Yiuman/bpmn-vue-activiti#44]
1、GIT拉下代码后npm i 正常运行。
2、任意控件表单输入内容绑定渲染错误，不能即时渲染，如：
![image](https://user-images.githubusercontent.com/5679249/209607993-1bc745bf-cad7-4f69-a253-25bced0717d9.png)
节点名称输入第一次1未渲染，输入第二次1渲染之前的内容
![image](https://user-images.githubusercontent.com/5679249/209608146-4233be31-60b8-4aa6-93fa-c26a2a4d289b.png)
此处每个数字均输入2次
![image](https://user-images.githubusercontent.com/5679249/209608199-a98265e8-5de0-46db-a519-6e063ea108d3.png)
此处表单key输入内容为123456

**Comment by Hack-DJ** [comment]
// state.handingModel[bindData.bindKey] = bindData.value;
context.emit('update:modelValue', state.handingModel);

测试把 state.handingModel[bindData.bindKey] = bindData.value; 去掉注释后ElInput控件能正常输入显示，但表单录入任然不能实时渲染，如：
1、表单信息添加第一条正常显示。
2、表单信息添加第二条不渲染，添加第三条渲染第二条内容。

**Comment by Yiuman** [comment]
> 1、GIT拉下代码后npm i 正常运行。
> 2、任意控件表单输入内容绑定渲染错误，不能即时渲染，如：
> ![image](https://user-images.githubusercontent.com/5679249/209607993-1bc745bf-cad7-4f69-a253-25bced0717d9.png)
> 节点名称输入第一次1未渲染，输入第二次1渲染之前的内容
> ![image](https://user-images.githubusercontent.com/5679249/209608146-4233be31-60b8-4aa6-93fa-c26a2a4d289b.png)
> 此处每个数字均输入2次
> ![image](https://user-images.githubusercontent.com/5679249/209608199-a98265e8-5de0-46db-a519-6e063ea108d3.png)
> 此处表单key输入内容为123456

方便提个PR吗

**Comment by Hack-DJ** [comment]
> > 1、GIT拉下代码后npm i 正常运行。
> > 2、任意控件表单输入内容绑定渲染错误，不能即时渲染，如：
> > ![image](https://user-images.githubusercontent.com/5679249/209607993-1bc745bf-cad7-4f69-a253-25bced0717d9.png)
> > 节点名称输入第一次1未渲染，输入第二次1渲染之前的内容
> > ![image](https://user-images.githubusercontent.com/5679249/209608146-4233be31-60b8-4aa6-93fa-c26a2a4d289b.png)
> > 此处每个数字均输入2次
> > ![image](https://user-images.githubusercontent.com/5679249/209608199-a98265e8-5de0-46db-a519-6e063ea108d3.png)
> > 此处表单key输入内容为123456
> 
> 方便提个PR吗

没有哦，我什么都没改，我就git clone xxxx 然后npm install 然后 npm run dev  表单就是这样输入后不能即时渲染，我大概看了下，是表单录入数据，bpmn内容更新了，element-ui的value没更新，但是当重新再输入的时候，就会把bpmn的值更新进去，

**Comment by auhouhs** [comment]
看一下node_modules下面引用的vue版本，是不是在3.2.28或者以上，如果是，锁定vue版本到3.2.27或者以下试试

**Comment by JinGuiMin** [comment]
为啥我这是正常的？ 
当输入节点名称的时候正常渲染

**Comment by JinGuiMin** [comment]
找到问题了，果然是没有收集到依赖导致的。
将DynamicBinder组件中的setValue和defaultTransformer方法中的toRaw去掉就正常了。

**Comment by Interstellar42** [comment]
> 找到问题了，果然是没有收集到依赖导致的。 将DynamicBinder组件中的setValue和defaultTransformer方法中的toRaw去掉就正常了。

我试了还是不起作用

**Comment by Yiuman** [comment]
> 

估计改漏了  我后边有空看下
