### ISSUE TITLE
端口只能是3000吗？

### ISSUE THREAD

**Issue by zsoftbuilder** [Yiuman/bpmn-vue-activiti#5]
端口只能是3000吗？能改成其它的吗？有没有vue.config.js这种可以配置代理端口的地方呢，或者其它地方能配置？

**Comment by Yiuman** [comment]
用的vite哦，可以去看看相关配置

**Comment by Yiuman** [comment]
@zsoftbuilder 你可以在vite.config.ts中加上
 server: {
    port: 你的端口
  }
  其他的相关配置请看 [](https://cn.vitejs.dev/)

**Comment by Yiuman** [comment]
https://cn.vitejs.dev/
