### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by HUAzd** [Yiuman/bpmn-vue-activiti#55]
![image](https://github.com/Yiuman/bpmn-vue-activiti/assets/44830285/a06c7b5a-2aad-4177-a2a5-c9387c73e0ea)

node版本：v16.17.1
npm版本：8.15.0
电脑系统：win10
代码分支：main

请问怎么解决呀

**Comment by Yiuman** [comment]
参考
node版本: v16.15.0
yarn版本：

**Comment by Yiuman** [comment]
参考
node版本：v16.15.0
yarn版本：1.22.17
看下是否是网络原因下载不了依赖，可以配个镜像
