### ISSUE TITLE
你好，更新最新代码后运行不起来，请问要怎么运行？

### ISSUE THREAD

**Issue by zsoftbuilder** [Yiuman/bpmn-vue-activiti#7]
我之前执行如下可以运行，现在不能运行，请问要如何直接运行？
npm install --registry=https://registry.npm.taobao.org;
npm run dev;

**Comment by Yiuman** [comment]
可以用yarn  
1.npm install --global yarn
2.yarn 
3.yarn dev

**Comment by zsoftbuilder** [comment]
按你的方式，报下面错
yarn : File C:\Users\soft\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ yarn dev
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by Yiuman** [comment]
装上yarn没？ yarn --version看下

**Comment by zsoftbuilder** [comment]
PS C:\workspace\myspace\vue\bpmn-vue-activiti> npm install --global yarn

changed 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
PS C:\workspace\myspace\vue\bpmn-vue-activiti>  yarn --version
yarn : File C:\Users\soft\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:2
+  yarn --version
+  ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by Yiuman** [comment]
用的powerShell吗，换gitbash试试

**Comment by zsoftbuilder** [comment]
请问一下，人员设置这块只能是选择呢？要是使用${assignee}或者${candidateUser}这种UEL表达式就没法设置了？这块设置应该使用文本框吧？文本框可以设置任何值包括UEL表达式

**Comment by Yiuman** [comment]
可以直接输入的
