### ISSUE TITLE
人员任务的人员设置里候选人 不能手动输入

### ISSUE THREAD

**Issue by zsoftbuilder** [Yiuman/bpmn-vue-activiti#8]
你好，人员任务的人员设置里候选人 不能手动输入，无法直接输入UEL表达式，只能选张三，李四这种无意义的角色？

**Comment by Yiuman** [comment]
1.每个业务系统的人员选择都不一样的，请自己设配
2.最新代码支持输入的，线上版本未更新，请自行拉取代码修改使用

**Comment by zsoftbuilder** [comment]
你好，我下的就是最新代码，本地运行的。线上的是处理人和候选人都不能输入，本地最新代码是处理人可以输入，但是候选人不能输入

**Comment by Yiuman** [comment]
这个按自己的需求调整下代码就行了。毕竟每个业务系统都不一样的需求

**Comment by zsoftbuilder** [comment]
谢谢！我对这块不是很熟悉，请问是修改哪部分呢？就是把候选人的选择框改成能任意输入字符

**Comment by Yiuman** [comment]
修改`src/bpmn/config/modules/Task.tsx`里的代码实现就有，参考现有的实现调整就可以了
